import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import Header from "./components/header";
import Footer from "./components/footer";

// 🔹 Load Poppins font
const poppins = Poppins({
  weight: ["300", "400", "500", "600", "700"], // optional: choose weights you need
  variable: "--font-poppins",
});

export const metadata: Metadata = {
  title: "5'oclock",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${poppins.variable} font-sans antialiased bg-gray-950 text-white`}
      >
        <Header />

        <main className="pt-24 min-h-screen">{children}</main>

        <Footer />
      </body>
    </html>
  );
}
